# Generated by Django 3.2.21 on 2023-10-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20231006_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='category',
            field=models.CharField(blank=True, choices=[('PR', 'Personal'), ('WR', 'Work'), ('ED', 'Education'), ('HL', 'Health')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
