# Generated by Django 3.2.21 on 2023-10-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20231010_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='category',
            field=models.CharField(blank=True, choices=[('PR', 'PERSONAL'), ('WR', 'WORK'), ('ED', 'EDUCATION'), ('HE', 'HEALTH')], max_length=150, null=True),
        ),
    ]
