# Generated by Django 3.2.21 on 2023-10-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_notes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='category',
            field=models.CharField(blank=True, choices=[('PR', 'Personal'), ('WR', 'Work'), ('ED', 'Education'), ('HE', 'Health')], default='PR', max_length=150, null=True),
        ),
    ]
