# Generated by Django 3.2.21 on 2023-10-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_notes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='category',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Work', 'Work'), ('Education', 'Education'), ('Health', 'Health')], max_length=150, null=True),
        ),
    ]
