# Generated by Django 3.2.21 on 2023-10-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_notes_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='priority',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], default='Low', max_length=150, null=True),
        ),
    ]
